export const REGISTER_FOR_VACCINE_REQUEST = 'REGISTER_FOR_VACCINE_REQUEST';
export const REGISTER_FOR_VACCINE_SUCCESS = 'REGISTER_FOR_VACCINE_SUCCESS';
export const REGISTER_FOR_VACCINE_FAILURE = 'REGISTER_FOR_VACCINE_FAILURE';

