export const GET_STAND_POINT_USER_REQUEST = 'GET_STAND_POINT_USER_REQUEST';
export const GET_STAND_POINT_USER_SUCCESS = 'GET_STAND_POINT_USER_SUCCESS';
export const GET_STAND_POINT_USER_FAILURE = 'GET_STAND_POINT_USER_FAILURE';

export const POST_STAND_POINT_AUTHORITY_REQUEST = 'POST_STAND_POINT_AUTHORITY_REQUEST';
export const POST_STAND_POINT_AUTHORITY_SUCCESS = 'POST_STAND_POINT_AUTHORITY_SUCCESS';
export const POST_STAND_POINT_AUTHORITY_FAILURE = 'POST_STAND_POINT_AUTHORITY_FAILURE';